version: '3.7'

x-base: &base
  logging:
    driver: "json-file"
    options:
      max-size: "3m"
      max-file: "1"
  # https://docs.docker.com/compose/compose-file/#restart
  restart: ${DOCKER_RESTART:-unless-stopped}

services:
  minecraft:
    <<: *base
    build:
      context: ./minecraft
    ports: ['25565:25565', '25575:25575']
    environment:
      MC_VER: ${MC_VER:-1.14.4}
      INIT_MEM: ${INIT_MEM:-2G}
      MAX_MEM: ${MAX_MEM:-4G}
    volumes:
      - ./minecraft/data:/data

  bukkit:
    <<: *base
    image: bbriggs/bukkit:${MC_VER:-1.14.4}
    ports: ['25565:25565', '25575:25575']
    env_file: bukkit.env

#volumes:
#  minecraft: {}
